# Generated by Django 5.2 on 2025-11-17 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='内部管理用の名前', max_length=200)),
                ('client_name', models.CharField(help_text='クライアント名（表示用）', max_length=200)),
                ('text', models.TextField(help_text='キャンペーンテキスト（Quote の text 相当）')),
                ('url', models.URLField(help_text='公式サイトURL')),
                ('sns_url', models.URLField(blank=True, help_text='SNS URL（任意）')),
                ('start_date', models.DateField(help_text='配信開始日')),
                ('end_date', models.DateField(help_text='配信終了日')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'キャンペーン',
                'verbose_name_plural': 'キャンペーン',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CampaignClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('official', '公式サイト'), ('sns', 'SNS'), ('share', 'Share')], default='official', max_length=20)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='tracking.campaign')),
            ],
            options={
                'verbose_name': 'Campaign クリックログ',
                'verbose_name_plural': 'Campaign クリックログ',
                'ordering': ['-clicked_at'],
                'indexes': [models.Index(fields=['campaign', 'action', 'clicked_at'], name='tracking_ca_campaig_9d3b79_idx'), models.Index(fields=['client_id', 'clicked_at'], name='tracking_ca_client__f4f78b_idx')],
            },
        ),
        migrations.CreateModel(
            name='CampaignView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='tracking.campaign')),
            ],
            options={
                'verbose_name': 'Campaign 表示ログ',
                'verbose_name_plural': 'Campaign 表示ログ',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['campaign', 'viewed_at'], name='tracking_ca_campaig_a367d8_idx'), models.Index(fields=['client_id', 'viewed_at'], name='tracking_ca_client__4aeaad_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuoteClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('wiki', 'Wikipedia'), ('amazon', 'Amazon'), ('share', 'Share')], max_length=20)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='quotes.quote')),
            ],
            options={
                'verbose_name': 'Quote クリックログ',
                'verbose_name_plural': 'Quote クリックログ',
                'ordering': ['-clicked_at'],
                'indexes': [models.Index(fields=['quote', 'action', 'clicked_at'], name='tracking_qu_quote_i_3c9b38_idx'), models.Index(fields=['client_id', 'clicked_at'], name='tracking_qu_client__006600_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuoteView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(help_text='匿名ユーザーID', max_length=100)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='quotes.quote')),
            ],
            options={
                'verbose_name': 'Quote 表示ログ',
                'verbose_name_plural': 'Quote 表示ログ',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['quote', 'viewed_at'], name='tracking_qu_quote_i_6323ec_idx'), models.Index(fields=['client_id', 'viewed_at'], name='tracking_qu_client__1bf5de_idx')],
            },
        ),
    ]
