# Generated by Django 5.2 on 2025-11-17 01:06

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='台詞本文')),
                ('original_text', models.TextField(blank=True, verbose_name='原文の台詞')),
                ('author_name', models.CharField(blank=True, help_text='例: シェイクスピア、太宰治', max_length=100, verbose_name='作者名')),
                ('source', models.CharField(blank=True, help_text='例: ハムレット、人間失格', max_length=200, verbose_name='出典')),
                ('original_source', models.CharField(blank=True, help_text='例: Hamlet, Cyrano de Bergerac', max_length=200, verbose_name='原題')),
                ('category', models.CharField(choices=[('classic', 'Classic'), ('drama', 'Drama'), ('comedy', 'Comedy'), ('love', 'Love'), ('horror', 'Horror'), ('other', 'Other')], default='other', max_length=20, verbose_name='カテゴリ')),
                ('tags', models.CharField(blank=True, help_text='例: 愛, 家族, 雨', max_length=200, verbose_name='タグ（カンマ区切り）')),
                ('publish_date', models.DateField(db_index=True, help_text='この日付の quote が『今日の1本』として扱われる', verbose_name='配信日（今日の1本になる日）')),
                ('is_public_domain', models.BooleanField(default=False, verbose_name='著作権切れ（公有）か？')),
                ('amazon_key', models.CharField(blank=True, help_text='ASIN or 検索用キーワード。空ならリンク無し', max_length=200, verbose_name='Amazonキー（ASIN or 検索キーワード）')),
                ('wiki_key', models.CharField(blank=True, help_text='Wikipedia検索用キーワード。空ならリンク無し', max_length=200, verbose_name='Wiki検索キーワード')),
                ('bg_image_url', models.URLField(blank=True, verbose_name='背景画像URL（Cloudinary など）')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='いいね数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'ordering': ['-publish_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('apple_id', models.CharField(blank=True, help_text='Apple Sign-In で取得した user identifier', max_length=255, null=True, unique=True, verbose_name='Apple ID')),
                ('is_premium', models.BooleanField(default=False, verbose_name='プレミアム購読中')),
                ('premium_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='プレミアム有効期限')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'ユーザー',
                'verbose_name_plural': 'ユーザー',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='クライアントID（端末UUIDなど）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='quotes.quote', verbose_name='台詞')),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='quotes_favo_user_id_97df7b_idx'), models.Index(fields=['client_id'], name='quotes_favo_client__771c1e_idx')],
            },
        ),
    ]
