# Generated by Django 5.1.2 on 2025-11-13 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='台詞本文')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='作者名・出典')),
                ('category', models.CharField(choices=[('classic', 'Classic'), ('drama', 'Drama'), ('comedy', 'Comedy'), ('love', 'Love'), ('horror', 'Horror'), ('other', 'Other')], default='other', max_length=20, verbose_name='カテゴリ')),
                ('tags', models.CharField(blank=True, help_text='例: 愛, 家族, 雨', max_length=200, verbose_name='タグ（カンマ区切り）')),
                ('publish_date', models.DateField(db_index=True, help_text='この日付の quote が『今日の1本』として扱われる', verbose_name='配信日（今日の1本になる日）')),
                ('is_public_domain', models.BooleanField(default=False, verbose_name='著作権切れ（公有）か？')),
                ('amazon_key', models.CharField(blank=True, help_text='ASIN or 検索用キーワード。空ならリンク無し', max_length=200, verbose_name='Amazonキー（ASIN or 検索キーワード）')),
                ('bg_image_url', models.URLField(blank=True, verbose_name='背景画像URL（Cloudinary など）')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='いいね数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'ordering': ['-publish_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=64, verbose_name='クライアントID（端末UUIDなど）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='quotes.quote', verbose_name='台詞')),
            ],
            options={
                'indexes': [models.Index(fields=['client_id'], name='quotes_favo_client__771c1e_idx')],
                'unique_together': {('quote', 'client_id')},
            },
        ),
    ]
