# Generated by Django 5.2 on 2025-11-17 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='campaign_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='tracking.Campaign の ID（Campaign のお気に入り用）', null=True, verbose_name='キャンペーンID'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='quotes.quote', verbose_name='台詞'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['campaign_id'], name='quotes_favo_campaig_611612_idx'),
        ),
    ]
