# Generated by Django 5.2 on 2025-11-14 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_split_author_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='wiki_key',
            field=models.CharField(blank=True, help_text='Wikipedia検索用キーワード。空ならリンク無し', max_length=200, verbose_name='Wiki検索キーワード'),
        ),
    ]
