# Generated by Django 5.2 on 2025-11-14 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_add_wiki_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='original_source',
            field=models.CharField(blank=True, help_text='例: Hamlet, Cyrano de Bergerac', max_length=200, verbose_name='原題'),
        ),
        migrations.AddField(
            model_name='quote',
            name='original_text',
            field=models.TextField(blank=True, verbose_name='原文の台詞'),
        ),
    ]
